import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ClientLayout from "@/components/ClientLayout"; // Importer le nouveau composant client
import { NotificationProvider } from "@/components/notifications/NotificationProvider"; 
import { ConfigProvider } from "antd";
import frFR from "antd/lib/locale/fr_FR";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <ConfigProvider locale={frFR}>
      <body className={inter.className}>
      <NotificationProvider>

        {/* Utilisez le ClientLayout pour gérer la logique de la Navbar */}
        <ClientLayout>{children}</ClientLayout>
        </NotificationProvider>
      </body>
      </ConfigProvider>
    </html>
  );
}
