"use client";

import React from "react";
import { useLocale } from "next-intl";
import { Link } from "@/i18n/navigation";
import LegalLayout from "@/components/LegalLayout";

const FrBody = () => (
  <>
    <p>
      Conformément aux dispositions des articles 6-III et 19 de la Loi n°2004-575 du 21 juin 2004
      pour la Confiance dans l&apos;Économie Numérique, dite L.C.E.N., il est porté à la connaissance
      des utilisateurs et visiteurs du site <strong>Seranya</strong> les présentes mentions légales.
    </p>

    <h2>Hébergement</h2>
    <p>
      Le site est hébergé sur <strong>Amazon Lightsail</strong>, une infrastructure fournie par
      Amazon Web Services (AWS). Le siège social d&apos;Amazon est situé à{" "}
      <strong>410 Terry Avenue North, Seattle, WA 98109-5210, États-Unis</strong>.
    </p>

    <h2>Images du site</h2>
    <p>
      Toutes les images présentes sur ce site ont été générées par une intelligence artificielle.
      Ces images sont libres de droits d&apos;auteur et peuvent être utilisées sans restriction dans
      le cadre du site.
    </p>

    <h2>Vie privée et données personnelles</h2>
    <p>
      Le traitement de vos données personnelles et vos droits en la matière sont détaillés dans notre{" "}
      <Link href="/confidentialite">politique de confidentialité</Link>. Vous pouvez exercer vos droits via
      notre <Link href="/rgpd">formulaire de demande d&apos;accès aux données</Link>.
    </p>

    <h2>Contact</h2>
    <p>
      Pour toute question ou réclamation, vous pouvez nous contacter à{" "}
      <strong>contact@seranya-blog.com</strong>.
    </p>
  </>
);

const EnBody = () => (
  <>
    <p>
      In accordance with articles 6-III and 19 of French Law No. 2004-575 of 21 June 2004 on
      Confidence in the Digital Economy (L.C.E.N.), the following legal notice is provided to the
      users and visitors of the <strong>Seranya</strong> website.
    </p>

    <h2>Hosting</h2>
    <p>
      The site is hosted on <strong>Amazon Lightsail</strong>, infrastructure provided by Amazon Web
      Services (AWS). Amazon&apos;s headquarters are located at{" "}
      <strong>410 Terry Avenue North, Seattle, WA 98109-5210, United States</strong>.
    </p>

    <h2>Site images</h2>
    <p>
      All images on this site were generated by an artificial intelligence. These images are free of
      copyright and may be used without restriction within the scope of the site.
    </p>

    <h2>Privacy and personal data</h2>
    <p>
      The processing of your personal data and your related rights are detailed in our{" "}
      <Link href="/confidentialite">privacy policy</Link>. You can exercise your rights through our{" "}
      <Link href="/rgpd">data access request form</Link>.
    </p>

    <h2>Contact</h2>
    <p>
      For any question or complaint, you can contact us at{" "}
      <strong>contact@seranya-blog.com</strong>.
    </p>
  </>
);

const MentionsLegalesPage = () => {
  const locale = useLocale();
  const isEn = locale === "en";
  return (
    <LegalLayout title={isEn ? "Legal notice" : "Mentions légales"}>
      {isEn ? <EnBody /> : <FrBody />}
    </LegalLayout>
  );
};

export default MentionsLegalesPage;
